// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/todo.proto

package todo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoStatus int32

const (
	TodoStatus_NEW        TodoStatus = 0
	TodoStatus_INPROGRESS TodoStatus = 1
	TodoStatus_DONE       TodoStatus = 2
)

var TodoStatus_name = map[int32]string{
	0: "NEW",
	1: "INPROGRESS",
	2: "DONE",
}

var TodoStatus_value = map[string]int32{
	"NEW":        0,
	"INPROGRESS": 1,
	"DONE":       2,
}

func (x TodoStatus) String() string {
	return proto.EnumName(TodoStatus_name, int32(x))
}

func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{0}
}

type Todo struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status               TodoStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=TodoStatus" json:"status,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Todo) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_NEW
}

func (m *Todo) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type AddTodoRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTodoRequest) Reset()         { *m = AddTodoRequest{} }
func (m *AddTodoRequest) String() string { return proto.CompactTextString(m) }
func (*AddTodoRequest) ProtoMessage()    {}
func (*AddTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{1}
}

func (m *AddTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTodoRequest.Unmarshal(m, b)
}
func (m *AddTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTodoRequest.Marshal(b, m, deterministic)
}
func (m *AddTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTodoRequest.Merge(m, src)
}
func (m *AddTodoRequest) XXX_Size() int {
	return xxx_messageInfo_AddTodoRequest.Size(m)
}
func (m *AddTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTodoRequest proto.InternalMessageInfo

func (m *AddTodoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTodoResponse) Reset()         { *m = AddTodoResponse{} }
func (m *AddTodoResponse) String() string { return proto.CompactTextString(m) }
func (*AddTodoResponse) ProtoMessage()    {}
func (*AddTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{2}
}

func (m *AddTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTodoResponse.Unmarshal(m, b)
}
func (m *AddTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTodoResponse.Marshal(b, m, deterministic)
}
func (m *AddTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTodoResponse.Merge(m, src)
}
func (m *AddTodoResponse) XXX_Size() int {
	return xxx_messageInfo_AddTodoResponse.Size(m)
}
func (m *AddTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTodoResponse proto.InternalMessageInfo

func (m *AddTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status               TodoStatus `protobuf:"varint,3,opt,name=status,proto3,enum=TodoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{3}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateTodoRequest) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_NEW
}

type UpdateTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoResponse) Reset()         { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()    {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{4}
}

func (m *UpdateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoResponse.Unmarshal(m, b)
}
func (m *UpdateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoResponse.Merge(m, src)
}
func (m *UpdateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoResponse.Size(m)
}
func (m *UpdateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoResponse proto.InternalMessageInfo

func (m *UpdateTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type ListTodoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoRequest) Reset()         { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()    {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{5}
}

func (m *ListTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoRequest.Unmarshal(m, b)
}
func (m *ListTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoRequest.Merge(m, src)
}
func (m *ListTodoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoRequest.Size(m)
}
func (m *ListTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoRequest proto.InternalMessageInfo

type ListTodoResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{6}
}

func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(m, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type DeleteTodoRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{7}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f52905b89a1b23f, []int{8}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func (m *DeleteTodoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("TodoStatus", TodoStatus_name, TodoStatus_value)
	proto.RegisterType((*Todo)(nil), "Todo")
	proto.RegisterType((*AddTodoRequest)(nil), "AddTodoRequest")
	proto.RegisterType((*AddTodoResponse)(nil), "AddTodoResponse")
	proto.RegisterType((*UpdateTodoRequest)(nil), "UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "UpdateTodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "ListTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "DeleteTodoResponse")
}

func init() { proto.RegisterFile("pb/todo.proto", fileDescriptor_1f52905b89a1b23f) }

var fileDescriptor_1f52905b89a1b23f = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xeb, 0x36, 0x6d, 0x97, 0x09, 0xb4, 0xe9, 0xec, 0x25, 0x84, 0x03, 0x91, 0xf7, 0x52,
	0x55, 0xe0, 0x48, 0xd9, 0x33, 0x87, 0x95, 0xb6, 0x42, 0x48, 0xa8, 0x8b, 0xdc, 0x45, 0x1c, 0x51,
	0x12, 0x9b, 0x55, 0xa4, 0x6e, 0x1d, 0xd6, 0x0e, 0x4f, 0xc2, 0x93, 0xf1, 0x44, 0x28, 0x76, 0x43,
	0xd3, 0x46, 0x82, 0x0b, 0xc7, 0x99, 0xfc, 0xf9, 0xe7, 0x9f, 0x6f, 0x0c, 0x2f, 0xaa, 0x3c, 0x31,
	0x4a, 0x28, 0x56, 0x3d, 0x29, 0xa3, 0xa2, 0xd7, 0x0f, 0x4a, 0x3d, 0xec, 0x64, 0x62, 0xab, 0xbc,
	0xfe, 0x96, 0x98, 0xf2, 0x51, 0x6a, 0x93, 0x3d, 0x56, 0x4e, 0x40, 0x7f, 0x12, 0xf0, 0xee, 0x95,
	0x50, 0x38, 0x83, 0x61, 0x29, 0x42, 0x12, 0x93, 0xe5, 0x98, 0x0f, 0x4b, 0x81, 0x21, 0x4c, 0x0b,
	0xb5, 0x37, 0x72, 0x6f, 0xc2, 0x61, 0x4c, 0x96, 0xcf, 0x78, 0x5b, 0xe2, 0x15, 0x4c, 0xb4, 0xc9,
	0x4c, 0xad, 0xc3, 0x51, 0x4c, 0x96, 0xb3, 0xd4, 0x67, 0x8d, 0xc1, 0xd6, 0xb6, 0xf8, 0xe1, 0x13,
	0xbe, 0x83, 0xe7, 0xbb, 0x4c, 0x9b, 0xaf, 0x75, 0x25, 0x32, 0x23, 0x45, 0xe8, 0xc5, 0x64, 0xe9,
	0xa7, 0x11, 0x73, 0x79, 0x58, 0x9b, 0x87, 0xdd, 0xb7, 0x79, 0xb8, 0xdf, 0xe8, 0x3f, 0x3b, 0x39,
	0x5d, 0xc1, 0xec, 0x46, 0x88, 0xc6, 0x97, 0xcb, 0xef, 0xb5, 0xd4, 0xa6, 0x9b, 0x87, 0x9c, 0xe4,
	0xa1, 0x6f, 0x60, 0xfe, 0x47, 0xab, 0x2b, 0xb5, 0xd7, 0x12, 0x5f, 0x82, 0xd7, 0x40, 0xb0, 0x4a,
	0x3f, 0x1d, 0xdb, 0x80, 0xdc, 0xb6, 0x68, 0x0e, 0x0b, 0x37, 0xa4, 0x6b, 0xfe, 0x7f, 0x97, 0xa7,
	0x09, 0x60, 0x77, 0xc6, 0xbf, 0x43, 0x2d, 0x60, 0xfe, 0xb1, 0xd4, 0xa6, 0x13, 0x89, 0x26, 0x10,
	0x1c, 0x5b, 0x07, 0x87, 0x57, 0x30, 0x6e, 0xe4, 0x3a, 0x24, 0xf1, 0xe8, 0x68, 0xe1, 0x7a, 0xf4,
	0x0a, 0x16, 0xb7, 0x72, 0x27, 0xff, 0xba, 0x18, 0x65, 0x80, 0x5d, 0xd1, 0xc1, 0x37, 0x84, 0xa9,
	0xae, 0x8b, 0x42, 0x6a, 0x6d, 0xa5, 0x17, 0xbc, 0x2d, 0x57, 0x09, 0xc0, 0x71, 0x3f, 0x9c, 0xc2,
	0x68, 0xb3, 0xfe, 0x12, 0x0c, 0x70, 0x06, 0xf0, 0x61, 0xf3, 0x89, 0xdf, 0xbd, 0xe7, 0xeb, 0xed,
	0x36, 0x20, 0x78, 0x01, 0xde, 0xed, 0xdd, 0x66, 0x1d, 0x0c, 0xd3, 0x5f, 0x04, 0x7c, 0xfb, 0x87,
	0x7c, 0xfa, 0x51, 0x16, 0x12, 0x57, 0x30, 0xba, 0x11, 0x02, 0xe7, 0xec, 0xf4, 0x9c, 0x51, 0xc0,
	0xce, 0x6e, 0x46, 0x07, 0x78, 0x0d, 0x13, 0x87, 0x0d, 0x91, 0xf5, 0x6e, 0x14, 0x5d, 0xb2, 0x3e,
	0x53, 0x3a, 0xc0, 0xb7, 0xe0, 0x35, 0x9c, 0x30, 0x60, 0x67, 0x04, 0xa3, 0x05, 0x3b, 0x07, 0xe8,
	0x66, 0x38, 0x00, 0x88, 0xac, 0x87, 0x2b, 0xba, 0x64, 0x7d, 0x3a, 0x74, 0x90, 0x4f, 0xec, 0x73,
	0xbd, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xe2, 0x73, 0x69, 0x5d, 0x03, 0x00, 0x00,
}
